SuperStore

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/Sample - Superstore.csv", encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

1st Quesion

In [ ]:
# Sales per Order & Region Analysis
sales_series = df.groupby('Order ID')['Sales'].sum()

region_stats = df.groupby('Region')['Sales'].describe()
print(region_stats)

          count        mean         std    min     25%     50%       75%  \
Region
Central  2323.0  215.772661  632.779010  0.444  14.620  45.980  200.0120
East     2848.0  238.336110  620.712652  0.852  17.520  54.900  209.6175
South    1620.0  241.803645  774.796273  1.167  17.187  54.594  208.7220
West     3203.0  226.493233  524.876877  0.990  19.440  60.840  215.8090

               max
Region
Central  17499.950
East     11199.968
South    22638.480
West     13999.960

**Conclusion** : Sales vary across regions, with some regions consistently showing higher average sales. This indicates regional demand differences and helps identify strong markets.

2nd Question

In [ ]:
# Profit Margin by Category & Sub-Category
group = df.groupby(['Category','Sub-Category']).agg({'Sales':'sum','Profit':'sum'})
group['ProfitMargin'] = group['Profit'] / group['Sales']

print(group.sort_values(by='ProfitMargin', ascending=False))

                                    Sales      Profit  ProfitMargin
Category        Sub-Category
Office Supplies Labels         12486.3120   5546.2540      0.444187
                Paper          78479.2060  34053.5693      0.433918
                Envelopes      16476.4020   6964.1767      0.422676
Technology      Copiers       149528.0300  55617.8249      0.371956
Office Supplies Fasteners       3024.2800    949.5182      0.313965
Technology      Accessories   167380.3180  41936.6357      0.250547
Office Supplies Art            27118.7920   6527.7870      0.240711
                Appliances    107532.1610  18138.0054      0.168675
                Binders       203412.7330  30221.7633      0.148574
Furniture       Furnishings    91705.1640  13059.1436      0.142404
Technology      Phones        330007.0540  44515.7306      0.134893
Office Supplies Storage       223843.6080  21278.8264      0.095061
Furniture       Chairs        328449.1030  26590.1663      0.080957
Technology      Machines      189238.6310   3384.7569      0.017886
Office Supplies Supplies       46673.5380  -1189.0995     -0.025477
Furniture       Bookcases     114879.9963  -3472.5560     -0.030228
                Tables        206965.5320 -17725.4811     -0.085645

**Conclusion** : Some sub-categories generate high profit margins, while others perform poorly or even at a loss. This helps identify which products are strong performers and which need improvement.

3rd Question

In [ ]:
#Hierarchical Indexing
df_multi = df.set_index(['Region','Category'])

result = df_multi.groupby(level=['Region','Category'])[['Sales','Profit']].sum()
print(result)

df_multi.xs('Furniture', level='Category')

                               Sales      Profit
Region  Category
Central Furniture        163797.1638  -2871.0494
        Office Supplies  167026.4150   8879.9799
        Technology       170416.3120  33697.4320
East    Furniture        208291.2040   3046.1658
        Office Supplies  205516.0550  41014.5791
        Technology       264973.9810  47462.0351
South   Furniture        117298.6840   6771.2061
        Office Supplies  125651.3130  19986.3928
        Technology       148771.9080  19991.8314
West    Furniture        252612.7435  11504.9503
        Office Supplies  220853.2490  52609.8490
        Technology       251991.8320  44303.6496

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Product ID,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Region,,,,,,,,,,,,,,,,,,,
South,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,FUR-BO-10001798,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
South,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,FUR-CH-10000454,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
South,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,FUR-TA-10000577,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
West,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,FUR-FU-10001487,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
West,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,FUR-TA-10001539,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Central,9963,CA-2015-168088,3/19/2015,3/22/2015,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,Texas,77041,FUR-BO-10004218,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
East,9965,CA-2016-146374,12/5/2016,12/10/2016,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,19711,FUR-FU-10002671,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320
South,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,Louisiana,70506,FUR-TA-10001039,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
South,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,FUR-FU-10001889,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
West,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,FUR-FU-10000747,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332

**Conclusion** : Hierarchical indexing shows how each category performs in different regions. It highlights regional strengths (high sales/profit) and weaknesses (low or negative profit)

4th Question

In [ ]:
# Profitability Score

df['NormProfit'] = (df['Profit'] - df['Profit'].min()) / (df['Profit'].max() - df['Profit'].min())
df['NormDiscount'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())
df['ProfitabilityScore'] = df['NormProfit'] - df['NormDiscount'] + np.log1p(df['Quantity'])

top_products = df.sort_values(by='ProfitabilityScore', ascending=False)
top_products.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,NormProfit,NormDiscount,ProfitabilityScore
9039,9040,CA-2016-117121,12/17/2016,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.74,13,0.0,4946.3700,0.769759,0.0,3.408816
1711,1712,CA-2017-123491,10/30/2017,11/5/2017,Standard Class,JK-15205,Jamie Kunitz,Consumer,United States,San Francisco,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",1702.12,14,0.0,510.6360,0.474042,0.0,3.182093
7387,7388,CA-2016-105732,9/13/2016,9/18/2016,Standard Class,AG-10270,Alejandro Grove,Consumer,United States,Omaha,...,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",1336.44,14,0.0,387.5676,0.465838,0.0,3.173888
1429,1430,US-2015-164448,10/31/2015,11/4/2015,Second Class,DK-12835,Damala Kotsonis,Corporate,United States,Salinas,...,Office Supplies,Labels,Avery 4027 File Folder Labels for Dot Matrix P...,427.42,14,0.0,196.6132,0.453107,0.0,3.161158
1433,1434,CA-2014-120768,12/19/2014,12/21/2014,Second Class,IM-15070,Irene Maddox,Consumer,United States,Florence,...,Furniture,Chairs,High-Back Leather Manager's Chair,1819.86,14,0.0,163.7874,0.450919,0.0,3.158969

**Conclusion** : The Profitability Score combines multiple factors to rank products more effectively. It helps identify top-performing items considering profit, discount, and quantity together.

5th Question

In [ ]:
# Null values
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Country               0
City                  0
State                 0
Postal Code           0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
NormProfit            0
NormDiscount          0
ProfitabilityScore    0
dtype: int64

In [ ]:
#drop rows
drop_df = df.dropna()

In [ ]:
#Fill with mean
df['Sales'] = df.groupby('Category')['Sales'].transform(lambda x: x.fillna(x.mean()))

**Conclusion** : Dropping null values may reduce data size and affect total revenue, while imputing preserves data. Using group-level mean is usually better for maintaining realistic values.

6th Question

In [ ]:
#Loss-making Orders
loss_df = df[(df['Discount'] > 0.3) & (df['Profit'] < 0)]

loss_analysis = loss_df.groupby('Sub-Category')['Profit'].mean()
print(loss_analysis)

Sub-Category
Appliances    -128.800615
Binders        -62.822996
Bookcases     -175.698147
Furnishings    -43.077212
Machines      -699.981353
Phones         -69.234845
Tables        -223.736846
Name: Profit, dtype: float64

**Conclusion** : High discounts often lead to negative profits, especially in certain sub-categories. This shows that excessive discounting can harm business performance.

7th Question

In [ ]:
# Shipping Performance
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [ ]:
#function
def shipping_status(row):
    if (row['Ship Date'] - row['Order Date']).days <= 3:
        return 'On-Time'
    else:
        return 'Delayed'

In [ ]:
df['ShippingStatus'] = df.apply(shipping_status, axis=1)

region_delay = df.groupby('Region')['ShippingStatus'].value_counts()
print(region_delay)

Region   ShippingStatus
Central  Delayed           1659
         On-Time            664
East     Delayed           1891
         On-Time            957
South    Delayed           1097
         On-Time            523
West     Delayed           2120
         On-Time           1083
Name: count, dtype: int64

**Conclusion**: Shipping delays vary by region, and some regions perform better than others. This helps identify areas where logistics need improvement.

8th Question

In [ ]:
# Index allignment
sales = df.groupby('Region')['Sales'].mean()
profit = df.groupby('Region')['Profit'].mean()

In [ ]:
# arthemetic Operations
result = sales + profit
print(result)

Region
Central    232.865369
East       270.471917
South      270.661318
West       260.342265
dtype: float64

**Conclusion**: Pandas aligns data automatically by region names. If any region is missing in one Series, the result shows NaN, highlighting mismatched indices.

9th question

In [ ]:
#Hierarchical Index
group = df.groupby(['Segment','Category']).agg({
    'Sales':'mean',
    'Profit':'mean',
    'Quantity':'mean'
})

matrix = group.unstack()
print(matrix)

                  Sales                                 Profit  \
Category      Furniture Office Supplies  Technology  Furniture
Segment
Consumer     351.347091      116.390194  427.339534   6.281293
Corporate    354.519792      126.745309  444.855810  11.741201
Home Office  336.825131      115.309021  535.976658  10.705465

                                        Quantity
Category    Office Supplies Technology Furniture Office Supplies Technology
Segment
Consumer          18.014174  74.445646  3.743037        3.760154   3.782334
Corporate         22.102923  79.723823  3.862229        3.856044   3.781588
Home Office       24.034439  89.152458  3.776243        3.827618   3.646199

**Conclusion** : This analysis shows how different customer segments perform across categories. It helps understand which segment-category combinations are most profitable.

10th Question

In [ ]:
# Final Report
summary = df.groupby(['Region','Category']).agg({
    'Sales':'sum',
    'Profit':'sum'
})

print(summary)

                               Sales      Profit
Region  Category
Central Furniture        163797.1638  -2871.0494
        Office Supplies  167026.4150   8879.9799
        Technology       170416.3120  33697.4320
East    Furniture        208291.2040   3046.1658
        Office Supplies  205516.0550  41014.5791
        Technology       264973.9810  47462.0351
South   Furniture        117298.6840   6771.2061
        Office Supplies  125651.3130  19986.3928
        Technology       148771.9080  19991.8314
West    Furniture        252612.7435  11504.9503
        Office Supplies  220853.2490  52609.8490
        Technology       251991.8320  44303.6496

**Conclusion** : A complete analysis combining null handling, grouping, and KPIs provides a clear view of business performance. It helps in better decision-making and strategy planning.